### ISSUE TITLE
Works!

### ISSUE THREAD

**Issue by thagoat** [indie-mirror/https-server#1]
Success! Running on Arch Linux server in France with node 11.10.0 =)
![screenshot from 2019-02-26 21-57-37](https://user-images.githubusercontent.com/16569070/53462396-a21a5300-3a11-11e9-9404-6eda3f85b15e.png)

**Comment by aral** [comment]
Awesome; thank you so much for letting me know :)

**Comment by aral** [comment]
[Updated the readme](https://github.com/indie-mirror/https-server/blob/master/README.md#thanks) so pacman is no longer listed as untested. Thanks again @thagoat :goat: :)

**Comment by thagoat** [comment]
Lol no problem. Great work on your part, thank you!
