### ISSUE TITLE
Windows 8.1 - x64 - OK

### ISSUE THREAD

**Issue by timknip** [indie-mirror/https-server#2]
![2019-02-28_1214](https://user-images.githubusercontent.com/48036/53562764-8b2f4a00-3b52-11e9-9eb2-3da2c7dfad4a.png)

**Comment by timknip** [comment]
Install pops up a windows dialog to allow adding the cert.
node 8.2.1
npm 6.1.0

**Comment by aral** [comment]
Hey Tim, thanks so much! I’ll document that people should expect a dialog. <strike>Apart from that it looks like it works, right? :)</strike>

(Ah, just saw the “OK” in your title. Neat! Will make that note about the dialog in the reader and close this.)

**Comment by aral** [comment]
Thanks again, Tim. Closing this now as I’ve updated the readme as of v4.0.0.
