### ISSUE TITLE
W10 Enterprise x64

### ISSUE THREAD

**Issue by neoanderthal** [indie-mirror/https-server#3]
Using Node 10.15.2 LTS (downloaded from node.js)

I receive the following message (might be my ineptitude, or related to Enterprise installations):

C:\https-server-master\bin>https-server
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'ansi-escape-sequences'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\https-server-master\bin\https-server.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

If I install ansi-escape-sequences, it seems to work fine (generates a self-signed cert, and is accessible at https://localhost).

EDIT: Only issue I've come across so far is that HTML files must use the .html extension - .htm aren't detected. (had a test site that used the .htm and kept getting 404 errors, but as soon as I changed the index page to .html it worked).

Additional Update: The ansi-escape-sequences must be something tied to the W10 Enterprise version I first tested on (W10E 2016 LTSB 1607).
I did a test install under W10 Pro 1709 using the Node 10.15.2 LTS and had no issues aside from the .html thing (which is not really an issue w/ https-server or node).

**Comment by neoanderthal** [comment]
> 
> 
> I receive the following message (might be my ineptitude, or related to Enterprise installations):
> 
> C:\https-server-master\bin>https-server
> internal/modules/cjs/loader.js:583
> throw err;
> ^
> Error: Cannot find module 'ansi-escape-sequences'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
> at Function.Module._load (internal/modules/cjs/loader.js:507:25)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (C:\https-server-master\bin\https-server.js:3:12)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)

If I install the ansi-escape-sequences package, it seems to run fine (i.e., certificate is generated, and the server is active on https://localhost).

**Comment by aral** [comment]
Thank you :)

I’m going to close this but please do let me know if you hit the issue with ansi-escape-sequences again. I just added it in 2.0.0.
